from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ArticleMultimediaInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, caption=None, copyright=None, format=None, height=None, subtype=None, type=None, url=None, width=None):  # noqa: E501
        """ArticleMultimediaInner - a model defined in OpenAPI

        :param caption: The caption of this ArticleMultimediaInner.  # noqa: E501
        :type caption: str
        :param copyright: The copyright of this ArticleMultimediaInner.  # noqa: E501
        :type copyright: str
        :param format: The format of this ArticleMultimediaInner.  # noqa: E501
        :type format: str
        :param height: The height of this ArticleMultimediaInner.  # noqa: E501
        :type height: int
        :param subtype: The subtype of this ArticleMultimediaInner.  # noqa: E501
        :type subtype: str
        :param type: The type of this ArticleMultimediaInner.  # noqa: E501
        :type type: str
        :param url: The url of this ArticleMultimediaInner.  # noqa: E501
        :type url: str
        :param width: The width of this ArticleMultimediaInner.  # noqa: E501
        :type width: int
        """
        self.openapi_types = {
            'caption': str,
            'copyright': str,
            'format': str,
            'height': int,
            'subtype': str,
            'type': str,
            'url': str,
            'width': int
        }

        self.attribute_map = {
            'caption': 'caption',
            'copyright': 'copyright',
            'format': 'format',
            'height': 'height',
            'subtype': 'subtype',
            'type': 'type',
            'url': 'url',
            'width': 'width'
        }

        self._caption = caption
        self._copyright = copyright
        self._format = format
        self._height = height
        self._subtype = subtype
        self._type = type
        self._url = url
        self._width = width

    @classmethod
    def from_dict(cls, dikt) -> 'ArticleMultimediaInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Article_multimedia_inner of this ArticleMultimediaInner.  # noqa: E501
        :rtype: ArticleMultimediaInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def caption(self) -> str:
        """Gets the caption of this ArticleMultimediaInner.


        :return: The caption of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption: str):
        """Sets the caption of this ArticleMultimediaInner.


        :param caption: The caption of this ArticleMultimediaInner.
        :type caption: str
        """

        self._caption = caption

    @property
    def copyright(self) -> str:
        """Gets the copyright of this ArticleMultimediaInner.


        :return: The copyright of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright: str):
        """Sets the copyright of this ArticleMultimediaInner.


        :param copyright: The copyright of this ArticleMultimediaInner.
        :type copyright: str
        """

        self._copyright = copyright

    @property
    def format(self) -> str:
        """Gets the format of this ArticleMultimediaInner.


        :return: The format of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this ArticleMultimediaInner.


        :param format: The format of this ArticleMultimediaInner.
        :type format: str
        """

        self._format = format

    @property
    def height(self) -> int:
        """Gets the height of this ArticleMultimediaInner.


        :return: The height of this ArticleMultimediaInner.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height: int):
        """Sets the height of this ArticleMultimediaInner.


        :param height: The height of this ArticleMultimediaInner.
        :type height: int
        """

        self._height = height

    @property
    def subtype(self) -> str:
        """Gets the subtype of this ArticleMultimediaInner.


        :return: The subtype of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._subtype

    @subtype.setter
    def subtype(self, subtype: str):
        """Sets the subtype of this ArticleMultimediaInner.


        :param subtype: The subtype of this ArticleMultimediaInner.
        :type subtype: str
        """

        self._subtype = subtype

    @property
    def type(self) -> str:
        """Gets the type of this ArticleMultimediaInner.


        :return: The type of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ArticleMultimediaInner.


        :param type: The type of this ArticleMultimediaInner.
        :type type: str
        """

        self._type = type

    @property
    def url(self) -> str:
        """Gets the url of this ArticleMultimediaInner.


        :return: The url of this ArticleMultimediaInner.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ArticleMultimediaInner.


        :param url: The url of this ArticleMultimediaInner.
        :type url: str
        """

        self._url = url

    @property
    def width(self) -> int:
        """Gets the width of this ArticleMultimediaInner.


        :return: The width of this ArticleMultimediaInner.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this ArticleMultimediaInner.


        :param width: The width of this ArticleMultimediaInner.
        :type width: int
        """

        self._width = width
