/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type AppInfoLocalizationResponse struct {

	Data AppInfoLocalization `json:"data"`

	Links DocumentLinks `json:"links"`
}

// AssertAppInfoLocalizationResponseRequired checks if the required fields are not zero-ed
func AssertAppInfoLocalizationResponseRequired(obj AppInfoLocalizationResponse) error {
	elements := map[string]interface{}{
		"data": obj.Data,
		"links": obj.Links,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAppInfoLocalizationRequired(obj.Data); err != nil {
		return err
	}
	if err := AssertDocumentLinksRequired(obj.Links); err != nil {
		return err
	}
	return nil
}

// AssertAppInfoLocalizationResponseConstraints checks if the values respects the defined constraints
func AssertAppInfoLocalizationResponseConstraints(obj AppInfoLocalizationResponse) error {
	return nil
}
