/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type PagedDocumentLinks struct {

	First string `json:"first,omitempty"`

	Next string `json:"next,omitempty"`

	Self string `json:"self"`
}

// AssertPagedDocumentLinksRequired checks if the required fields are not zero-ed
func AssertPagedDocumentLinksRequired(obj PagedDocumentLinks) error {
	elements := map[string]interface{}{
		"self": obj.Self,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPagedDocumentLinksConstraints checks if the values respects the defined constraints
func AssertPagedDocumentLinksConstraints(obj PagedDocumentLinks) error {
	return nil
}
