/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.4.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type BundleIdCreateRequestDataAttributes struct {

	Identifier string `json:"identifier"`

	Name string `json:"name"`

	Platform BundleIdPlatform `json:"platform"`

	SeedId string `json:"seedId,omitempty"`
}

// AssertBundleIdCreateRequestDataAttributesRequired checks if the required fields are not zero-ed
func AssertBundleIdCreateRequestDataAttributesRequired(obj BundleIdCreateRequestDataAttributes) error {
	elements := map[string]interface{}{
		"identifier": obj.Identifier,
		"name": obj.Name,
		"platform": obj.Platform,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBundleIdCreateRequestDataAttributesConstraints checks if the values respects the defined constraints
func AssertBundleIdCreateRequestDataAttributesConstraints(obj BundleIdCreateRequestDataAttributes) error {
	return nil
}
