/*
 * Open Banking - Payments initiation service
 *
 * Open Banking - Payments initiation service
 *
 * API version: 1.16.0
 * Contact: apisupport@mastercard.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LogoFileType : Type of the uploaded Logo file
type LogoFileType string

// List of LogoFileType
const (
	PNG LogoFileType = "png"
	JPG LogoFileType = "jpg"
	SVG LogoFileType = "svg"
)
