/*
 * Open Banking - Payments initiation service
 *
 * Open Banking - Payments initiation service
 *
 * API version: 1.16.0
 * Contact: apisupport@mastercard.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostPaymentsSepaCreditTransfersPaymentStatusOkBody struct {

	OriginalRequestInfo PostPaymentsSepaCreditTransfersPaymentStatusOkBodyOriginalRequestInfo `json:"originalRequestInfo"`

	Payments PostPaymentsSepaCreditTransfersPaymentStatusOkBodyPayments `json:"payments,omitempty"`
}
