/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ProjectSaveAsTemplateRequest struct {

	Data ProjectSaveAsTemplateRequest `json:"data,omitempty"`
}

// AssertProjectSaveAsTemplateRequestRequired checks if the required fields are not zero-ed
func AssertProjectSaveAsTemplateRequestRequired(obj ProjectSaveAsTemplateRequest) error {
	if err := AssertProjectSaveAsTemplateRequestRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertProjectSaveAsTemplateRequestConstraints checks if the values respects the defined constraints
func AssertProjectSaveAsTemplateRequestConstraints(obj ProjectSaveAsTemplateRequest) error {
	return nil
}
