/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type DuplicateTaskRequest struct {

	Data TaskDuplicateRequest `json:"data,omitempty"`
}

// AssertDuplicateTaskRequestRequired checks if the required fields are not zero-ed
func AssertDuplicateTaskRequestRequired(obj DuplicateTaskRequest) error {
	if err := AssertTaskDuplicateRequestRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertDuplicateTaskRequestConstraints checks if the values respects the defined constraints
func AssertDuplicateTaskRequestConstraints(obj DuplicateTaskRequest) error {
	return nil
}
