/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type DependentFlagLinks struct {

	Self Link `json:"self,omitempty"`
}

// AssertDependentFlagLinksRequired checks if the required fields are not zero-ed
func AssertDependentFlagLinksRequired(obj DependentFlagLinks) error {
	if err := AssertLinkRequired(obj.Self); err != nil {
		return err
	}
	return nil
}

// AssertDependentFlagLinksConstraints checks if the values respects the defined constraints
func AssertDependentFlagLinksConstraints(obj DependentFlagLinks) error {
	return nil
}
