/*
 * CircleCI REST API
 *
 * The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI. You can access all information and trigger all actions. The only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Outcome string

// List of Outcome
const (
	CANCELED Outcome = "canceled"
	INFRASTRUCTURE_FAIL Outcome = "infrastructure_fail"
	TIMEDOUT Outcome = "timedout"
	FAILED Outcome = "failed"
	NO_TESTS Outcome = "no_tests"
	SUCCESS Outcome = "success"
)
