from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PingRequestDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ping=None):  # noqa: E501
        """PingRequestDto - a model defined in OpenAPI

        :param ping: The ping of this PingRequestDto.  # noqa: E501
        :type ping: int
        """
        self.openapi_types = {
            'ping': int
        }

        self.attribute_map = {
            'ping': 'Ping'
        }

        self._ping = ping

    @classmethod
    def from_dict(cls, dikt) -> 'PingRequestDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PingRequestDto of this PingRequestDto.  # noqa: E501
        :rtype: PingRequestDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ping(self) -> int:
        """Gets the ping of this PingRequestDto.

        Gets or sets the ping time.  # noqa: E501

        :return: The ping of this PingRequestDto.
        :rtype: int
        """
        return self._ping

    @ping.setter
    def ping(self, ping: int):
        """Sets the ping of this PingRequestDto.

        Gets or sets the ping time.  # noqa: E501

        :param ping: The ping of this PingRequestDto.
        :type ping: int
        """

        self._ping = ping
