/*
 * Open Banking - Payments initiation service
 *
 * Open Banking - Payments initiation service
 *
 * API version: 1.16.0
 * Contact: apisupport@mastercard.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type PostPaymentsSepaCreditTransfersOkBody struct {

	Consent SepaPaymentConsent `json:"consent"`

	OriginalRequestInfo PostPaymentsSepaCreditTransfersOkBodyOriginalRequestInfo `json:"originalRequestInfo"`

	Transfer PostPaymentsSepaCreditTransfersOkBodyTransfer `json:"transfer"`
}

// AssertPostPaymentsSepaCreditTransfersOkBodyRequired checks if the required fields are not zero-ed
func AssertPostPaymentsSepaCreditTransfersOkBodyRequired(obj PostPaymentsSepaCreditTransfersOkBody) error {
	elements := map[string]interface{}{
		"consent": obj.Consent,
		"originalRequestInfo": obj.OriginalRequestInfo,
		"transfer": obj.Transfer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSepaPaymentConsentRequired(obj.Consent); err != nil {
		return err
	}
	if err := AssertPostPaymentsSepaCreditTransfersOkBodyOriginalRequestInfoRequired(obj.OriginalRequestInfo); err != nil {
		return err
	}
	if err := AssertPostPaymentsSepaCreditTransfersOkBodyTransferRequired(obj.Transfer); err != nil {
		return err
	}
	return nil
}

// AssertPostPaymentsSepaCreditTransfersOkBodyConstraints checks if the values respects the defined constraints
func AssertPostPaymentsSepaCreditTransfersOkBodyConstraints(obj PostPaymentsSepaCreditTransfersOkBody) error {
	return nil
}
