/*
 * Open Banking - Payments initiation service
 *
 * Open Banking - Payments initiation service
 *
 * API version: 1.16.0
 * Contact: apisupport@mastercard.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type PostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgent struct {

	// Debtor FI
	Bicfi string `json:"bicfi"`
}

// AssertPostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgentRequired checks if the required fields are not zero-ed
func AssertPostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgentRequired(obj PostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgent) error {
	elements := map[string]interface{}{
		"bicfi": obj.Bicfi,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgentConstraints checks if the values respects the defined constraints
func AssertPostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgentConstraints(obj PostPaymentsSepaCreditTransfersConsentsParamsBodyPaymentsDebtorAgent) error {
	return nil
}
