/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Avatar - Details of an avatar.
type Avatar struct {

	// The file name of the avatar icon. Returned for system avatars.
	FileName string `json:"fileName,omitempty"`

	// The ID of the avatar.
	Id string `json:"id"`

	// Whether the avatar can be deleted.
	IsDeletable bool `json:"isDeletable,omitempty"`

	// Whether the avatar is used in Jira. For example, shown as a project's avatar.
	IsSelected bool `json:"isSelected,omitempty"`

	// Whether the avatar is a system avatar.
	IsSystemAvatar bool `json:"isSystemAvatar,omitempty"`

	// The owner of the avatar. For a system avatar the owner is null (and nothing is returned). For non-system avatars this is the appropriate identifier, such as the ID for a project or the account ID for a user.
	Owner string `json:"owner,omitempty"`

	// The list of avatar icon URLs.
	Urls map[string]string `json:"urls,omitempty"`
}

// AssertAvatarRequired checks if the required fields are not zero-ed
func AssertAvatarRequired(obj Avatar) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAvatarConstraints checks if the values respects the defined constraints
func AssertAvatarConstraints(obj Avatar) error {
	return nil
}
