/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ConfigurationTimeTrackingConfiguration - The configuration of time tracking.
type ConfigurationTimeTrackingConfiguration struct {

	// The default unit of time applied to logged time.
	DefaultUnit string `json:"defaultUnit"`

	// The format that will appear on an issue's *Time Spent* field.
	TimeFormat string `json:"timeFormat"`

	// The number of days in a working week.
	WorkingDaysPerWeek float64 `json:"workingDaysPerWeek"`

	// The number of hours in a working day.
	WorkingHoursPerDay float64 `json:"workingHoursPerDay"`
}

// AssertConfigurationTimeTrackingConfigurationRequired checks if the required fields are not zero-ed
func AssertConfigurationTimeTrackingConfigurationRequired(obj ConfigurationTimeTrackingConfiguration) error {
	elements := map[string]interface{}{
		"defaultUnit": obj.DefaultUnit,
		"timeFormat": obj.TimeFormat,
		"workingDaysPerWeek": obj.WorkingDaysPerWeek,
		"workingHoursPerDay": obj.WorkingHoursPerDay,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertConfigurationTimeTrackingConfigurationConstraints checks if the values respects the defined constraints
func AssertConfigurationTimeTrackingConfigurationConstraints(obj ConfigurationTimeTrackingConfiguration) error {
	return nil
}
