/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ErrorCollection - Error messages from an operation.
type ErrorCollection struct {

	// The list of error messages produced by this operation. For example, \"input parameter 'key' must be provided\"
	ErrorMessages []string `json:"errorMessages,omitempty"`

	// The list of errors by parameter returned by the operation. For example,\"projectKey\": \"Project keys must start with an uppercase letter, followed by one or more uppercase alphanumeric characters.\"
	Errors map[string]string `json:"errors,omitempty"`

	Status int32 `json:"status,omitempty"`
}

// AssertErrorCollectionRequired checks if the required fields are not zero-ed
func AssertErrorCollectionRequired(obj ErrorCollection) error {
	return nil
}

// AssertErrorCollectionConstraints checks if the values respects the defined constraints
func AssertErrorCollectionConstraints(obj ErrorCollection) error {
	return nil
}
