/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// IssueLinkTypes - A list of issue link type beans.
type IssueLinkTypes struct {

	// The issue link type bean.
	IssueLinkTypes []IssueLinkType `json:"issueLinkTypes,omitempty"`
}

// AssertIssueLinkTypesRequired checks if the required fields are not zero-ed
func AssertIssueLinkTypesRequired(obj IssueLinkTypes) error {
	for _, el := range obj.IssueLinkTypes {
		if err := AssertIssueLinkTypeRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertIssueLinkTypesConstraints checks if the values respects the defined constraints
func AssertIssueLinkTypesConstraints(obj IssueLinkTypes) error {
	return nil
}
