/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// LinkedIssueFields - The fields associated with the issue.
type LinkedIssueFields struct {

	Assignee FieldsAssignee `json:"assignee,omitempty"`

	IssueType FieldsIssueType `json:"issueType,omitempty"`

	Issuetype IssueTypeDetails `json:"issuetype,omitempty"`

	Priority FieldsPriority `json:"priority,omitempty"`

	Status FieldsStatus `json:"status,omitempty"`

	// The summary description of the linked issue.
	Summary string `json:"summary,omitempty"`

	Timetracking FieldsTimetracking `json:"timetracking,omitempty"`
}

// AssertLinkedIssueFieldsRequired checks if the required fields are not zero-ed
func AssertLinkedIssueFieldsRequired(obj LinkedIssueFields) error {
	if err := AssertFieldsAssigneeRequired(obj.Assignee); err != nil {
		return err
	}
	if err := AssertFieldsIssueTypeRequired(obj.IssueType); err != nil {
		return err
	}
	if err := AssertIssueTypeDetailsRequired(obj.Issuetype); err != nil {
		return err
	}
	if err := AssertFieldsPriorityRequired(obj.Priority); err != nil {
		return err
	}
	if err := AssertFieldsStatusRequired(obj.Status); err != nil {
		return err
	}
	if err := AssertFieldsTimetrackingRequired(obj.Timetracking); err != nil {
		return err
	}
	return nil
}

// AssertLinkedIssueFieldsConstraints checks if the values respects the defined constraints
func AssertLinkedIssueFieldsConstraints(obj LinkedIssueFields) error {
	return nil
}
