/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// IssuePickerSuggestionsIssueType - A type of issue suggested for use in auto-completion.
type IssuePickerSuggestionsIssueType struct {

	// The ID of the type of issues suggested for use in auto-completion.
	Id string `json:"id,omitempty"`

	// A list of issues suggested for use in auto-completion.
	Issues []SuggestedIssue `json:"issues,omitempty"`

	// The label of the type of issues suggested for use in auto-completion.
	Label string `json:"label,omitempty"`

	// If no issue suggestions are found, returns a message indicating no suggestions were found,
	Msg string `json:"msg,omitempty"`

	// If issue suggestions are found, returns a message indicating the number of issues suggestions found and returned.
	Sub string `json:"sub,omitempty"`
}

// AssertIssuePickerSuggestionsIssueTypeRequired checks if the required fields are not zero-ed
func AssertIssuePickerSuggestionsIssueTypeRequired(obj IssuePickerSuggestionsIssueType) error {
	for _, el := range obj.Issues {
		if err := AssertSuggestedIssueRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertIssuePickerSuggestionsIssueTypeConstraints checks if the values respects the defined constraints
func AssertIssuePickerSuggestionsIssueTypeConstraints(obj IssuePickerSuggestionsIssueType) error {
	return nil
}
