/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type LinkIssueRequestJsonBean struct {

	Comment Comment `json:"comment,omitempty"`

	InwardIssue LinkedIssue `json:"inwardIssue"`

	OutwardIssue LinkedIssue `json:"outwardIssue"`

	Type IssueLinkType `json:"type"`
}

// AssertLinkIssueRequestJsonBeanRequired checks if the required fields are not zero-ed
func AssertLinkIssueRequestJsonBeanRequired(obj LinkIssueRequestJsonBean) error {
	elements := map[string]interface{}{
		"inwardIssue": obj.InwardIssue,
		"outwardIssue": obj.OutwardIssue,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertLinkedIssueRequired(obj.InwardIssue); err != nil {
		return err
	}
	if err := AssertLinkedIssueRequired(obj.OutwardIssue); err != nil {
		return err
	}
	if err := AssertIssueLinkTypeRequired(obj.Type); err != nil {
		return err
	}
	return nil
}

// AssertLinkIssueRequestJsonBeanConstraints checks if the values respects the defined constraints
func AssertLinkIssueRequestJsonBeanConstraints(obj LinkIssueRequestJsonBean) error {
	return nil
}
