/*
 * College Football Data API
 *
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * API version: 4.4.12
 * Contact: admin@collegefootballdata.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdvancedSeasonStatDefense struct {

	Drives int32 `json:"drives,omitempty"`

	Explosiveness float32 `json:"explosiveness,omitempty"`

	FieldPosition AdvancedSeasonStatDefenseFieldPosition `json:"fieldPosition,omitempty"`

	Havoc AdvancedSeasonStatDefenseHavoc `json:"havoc,omitempty"`

	LineYards float32 `json:"lineYards,omitempty"`

	LineYardsTotal float32 `json:"lineYardsTotal,omitempty"`

	OpenFieldYards float32 `json:"openFieldYards,omitempty"`

	OpenFieldYardsTotal int32 `json:"openFieldYardsTotal,omitempty"`

	PassingDowns AdvancedSeasonStatDefensePassingDowns `json:"passingDowns,omitempty"`

	PassingPlays AdvancedSeasonStatDefensePassingPlays `json:"passingPlays,omitempty"`

	Plays int32 `json:"plays,omitempty"`

	PointsPerOpportunity float32 `json:"pointsPerOpportunity,omitempty"`

	PowerSuccess float32 `json:"powerSuccess,omitempty"`

	Ppa float32 `json:"ppa,omitempty"`

	RushingPlays AdvancedSeasonStatDefensePassingPlays `json:"rushingPlays,omitempty"`

	SecondLevelYards float32 `json:"secondLevelYards,omitempty"`

	SecondLevelYardsTotal int32 `json:"secondLevelYardsTotal,omitempty"`

	StandardDowns AdvancedSeasonStatDefensePassingDowns `json:"standardDowns,omitempty"`

	StuffRate float32 `json:"stuffRate,omitempty"`

	SuccessRate float32 `json:"successRate,omitempty"`

	TotalOpportunies int32 `json:"totalOpportunies,omitempty"`

	TotalPPA float32 `json:"totalPPA,omitempty"`
}
