/*
 * Bills API
 *
 * API to get and search for information regarding Bills, their stages, associated amendments and publications.
 *
 * API version: v1
 * Contact: softwareengineering@parliament.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type BillPublication struct {

	DisplayDate time.Time `json:"displayDate,omitempty"`

	Files *[]PublicationDocument `json:"files,omitempty"`

	House House `json:"house,omitempty"`

	Id int32 `json:"id,omitempty"`

	Links *[]PublicationLink `json:"links,omitempty"`

	PublicationType PublicationType `json:"publicationType,omitempty"`

	Title *string `json:"title,omitempty"`
}

// AssertBillPublicationRequired checks if the required fields are not zero-ed
func AssertBillPublicationRequired(obj BillPublication) error {
	if obj.Files != nil {
		for _, el := range *obj.Files {
			if err := AssertPublicationDocumentRequired(el); err != nil {
				return err
			}
		}
	}
	if obj.Links != nil {
		for _, el := range *obj.Links {
			if err := AssertPublicationLinkRequired(el); err != nil {
				return err
			}
		}
	}
	if err := AssertPublicationTypeRequired(obj.PublicationType); err != nil {
		return err
	}
	return nil
}

// AssertBillPublicationConstraints checks if the values respects the defined constraints
func AssertBillPublicationConstraints(obj BillPublication) error {
	return nil
}
