from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeleteServiceLinkedRoleRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, role_name=None):  # noqa: E501
        """DeleteServiceLinkedRoleRequest - a model defined in OpenAPI

        :param role_name: The role_name of this DeleteServiceLinkedRoleRequest.  # noqa: E501
        :type role_name: str
        """
        self.openapi_types = {
            'role_name': str
        }

        self.attribute_map = {
            'role_name': 'RoleName'
        }

        self._role_name = role_name

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteServiceLinkedRoleRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteServiceLinkedRoleRequest of this DeleteServiceLinkedRoleRequest.  # noqa: E501
        :rtype: DeleteServiceLinkedRoleRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def role_name(self) -> str:
        """Gets the role_name of this DeleteServiceLinkedRoleRequest.


        :return: The role_name of this DeleteServiceLinkedRoleRequest.
        :rtype: str
        """
        return self._role_name

    @role_name.setter
    def role_name(self, role_name: str):
        """Sets the role_name of this DeleteServiceLinkedRoleRequest.


        :param role_name: The role_name of this DeleteServiceLinkedRoleRequest.
        :type role_name: str
        """
        if role_name is None:
            raise ValueError("Invalid value for `role_name`, must not be `None`")  # noqa: E501

        self._role_name = role_name
