/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ScreensAPI struct {
}

// Post /rest/api/3/screens/addToDefault/:fieldId
// Add field to default screen 
func (api *ScreensAPI) AddFieldToDefaultScreen(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /rest/api/3/screens
// Create screen 
func (api *ScreensAPI) CreateScreen(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /rest/api/3/screens/:screenId
// Delete screen 
func (api *ScreensAPI) DeleteScreen(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /rest/api/3/screens/:screenId/availableFields
// Get available screen fields 
func (api *ScreensAPI) GetAvailableScreenFields(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /rest/api/3/screens
// Get screens 
func (api *ScreensAPI) GetScreens(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /rest/api/3/field/:fieldId/screens
// Get screens for a field 
func (api *ScreensAPI) GetScreensForField(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /rest/api/3/screens/:screenId
// Update screen 
func (api *ScreensAPI) UpdateScreen(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

