/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProjectIssueTypes - Projects and issue types where the status is used. Only available if the `usages` expand is requested.
type ProjectIssueTypes struct {

	// IDs of the issue types
	IssueTypes []string `json:"issueTypes,omitempty"`

	Project ProjectId `json:"project,omitempty"`
}
