/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FieldDetails - Details about a field.
type FieldDetails struct {

	// The names that can be used to reference the field in an advanced search. For more information, see [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ).
	ClauseNames []string `json:"clauseNames,omitempty"`

	// Whether the field is a custom field.
	Custom bool `json:"custom,omitempty"`

	// The ID of the field.
	Id string `json:"id,omitempty"`

	// The key of the field.
	Key string `json:"key,omitempty"`

	// The name of the field.
	Name string `json:"name,omitempty"`

	// Whether the field can be used as a column on the issue navigator.
	Navigable bool `json:"navigable,omitempty"`

	// Whether the content of the field can be used to order lists.
	Orderable bool `json:"orderable,omitempty"`

	Schema JsonTypeBean `json:"schema,omitempty"`

	Scope Scope `json:"scope,omitempty"`

	// Whether the content of the field can be searched.
	Searchable bool `json:"searchable,omitempty"`
}
