from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.app_store_version_localization_update_request_data import AppStoreVersionLocalizationUpdateRequestData
from openapi_server import util

from openapi_server.models.app_store_version_localization_update_request_data import AppStoreVersionLocalizationUpdateRequestData  # noqa: E501

class AppStoreVersionLocalizationUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """AppStoreVersionLocalizationUpdateRequest - a model defined in OpenAPI

        :param data: The data of this AppStoreVersionLocalizationUpdateRequest.  # noqa: E501
        :type data: AppStoreVersionLocalizationUpdateRequestData
        """
        self.openapi_types = {
            'data': AppStoreVersionLocalizationUpdateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AppStoreVersionLocalizationUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppStoreVersionLocalizationUpdateRequest of this AppStoreVersionLocalizationUpdateRequest.  # noqa: E501
        :rtype: AppStoreVersionLocalizationUpdateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> AppStoreVersionLocalizationUpdateRequestData:
        """Gets the data of this AppStoreVersionLocalizationUpdateRequest.


        :return: The data of this AppStoreVersionLocalizationUpdateRequest.
        :rtype: AppStoreVersionLocalizationUpdateRequestData
        """
        return self._data

    @data.setter
    def data(self, data: AppStoreVersionLocalizationUpdateRequestData):
        """Sets the data of this AppStoreVersionLocalizationUpdateRequest.


        :param data: The data of this AppStoreVersionLocalizationUpdateRequest.
        :type data: AppStoreVersionLocalizationUpdateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
