from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.beta_tester_relationships_apps import BetaTesterRelationshipsApps
from openapi_server import util

from openapi_server.models.beta_tester_relationships_apps import BetaTesterRelationshipsApps  # noqa: E501

class InAppPurchaseRelationships(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, apps=None):  # noqa: E501
        """InAppPurchaseRelationships - a model defined in OpenAPI

        :param apps: The apps of this InAppPurchaseRelationships.  # noqa: E501
        :type apps: BetaTesterRelationshipsApps
        """
        self.openapi_types = {
            'apps': BetaTesterRelationshipsApps
        }

        self.attribute_map = {
            'apps': 'apps'
        }

        self._apps = apps

    @classmethod
    def from_dict(cls, dikt) -> 'InAppPurchaseRelationships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InAppPurchase_relationships of this InAppPurchaseRelationships.  # noqa: E501
        :rtype: InAppPurchaseRelationships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def apps(self) -> BetaTesterRelationshipsApps:
        """Gets the apps of this InAppPurchaseRelationships.


        :return: The apps of this InAppPurchaseRelationships.
        :rtype: BetaTesterRelationshipsApps
        """
        return self._apps

    @apps.setter
    def apps(self, apps: BetaTesterRelationshipsApps):
        """Sets the apps of this InAppPurchaseRelationships.


        :param apps: The apps of this InAppPurchaseRelationships.
        :type apps: BetaTesterRelationshipsApps
        """

        self._apps = apps
