/*
 * Mastodon API Specification (https://github.com/mastodon/mastodon)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: sardo@hey.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Context - Represents the tree around a given status. Used for reconstructing threads of statuses.
type Context struct {

	// Parents in the thread.
	Ancestors []Status `json:"ancestors"`

	// Children in the thread.
	Descendants []Status `json:"descendants"`
}
