/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets MetadataRefreshMode
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<MetadataRefreshMode>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MetadataRefreshMode
        {
            
            /// <summary>
            /// Enum NoneEnum for None
            /// </summary>
            [EnumMember(Value = "None")]
            NoneEnum = 1,
            
            /// <summary>
            /// Enum ValidationOnlyEnum for ValidationOnly
            /// </summary>
            [EnumMember(Value = "ValidationOnly")]
            ValidationOnlyEnum = 2,
            
            /// <summary>
            /// Enum DefaultEnum for Default
            /// </summary>
            [EnumMember(Value = "Default")]
            DefaultEnum = 3,
            
            /// <summary>
            /// Enum FullRefreshEnum for FullRefresh
            /// </summary>
            [EnumMember(Value = "FullRefresh")]
            FullRefreshEnum = 4
        }
}
