/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PlayMethod string

// List of PlayMethod
const (
	TRANSCODE PlayMethod = "Transcode"
	DIRECT_STREAM PlayMethod = "DirectStream"
	DIRECT_PLAY PlayMethod = "DirectPlay"
)
