from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Address(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, addr=None, prefix_len=None):  # noqa: E501
        """Address - a model defined in OpenAPI

        :param addr: The addr of this Address.  # noqa: E501
        :type addr: str
        :param prefix_len: The prefix_len of this Address.  # noqa: E501
        :type prefix_len: int
        """
        self.openapi_types = {
            'addr': str,
            'prefix_len': int
        }

        self.attribute_map = {
            'addr': 'Addr',
            'prefix_len': 'PrefixLen'
        }

        self._addr = addr
        self._prefix_len = prefix_len

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def addr(self) -> str:
        """Gets the addr of this Address.

        IP address.  # noqa: E501

        :return: The addr of this Address.
        :rtype: str
        """
        return self._addr

    @addr.setter
    def addr(self, addr: str):
        """Sets the addr of this Address.

        IP address.  # noqa: E501

        :param addr: The addr of this Address.
        :type addr: str
        """

        self._addr = addr

    @property
    def prefix_len(self) -> int:
        """Gets the prefix_len of this Address.

        Mask length of the IP address.  # noqa: E501

        :return: The prefix_len of this Address.
        :rtype: int
        """
        return self._prefix_len

    @prefix_len.setter
    def prefix_len(self, prefix_len: int):
        """Sets the prefix_len of this Address.

        Mask length of the IP address.  # noqa: E501

        :param prefix_len: The prefix_len of this Address.
        :type prefix_len: int
        """

        self._prefix_len = prefix_len
