from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.object_version import ObjectVersion
from openapi_server.models.service_endpoint import ServiceEndpoint
from openapi_server.models.service_spec import ServiceSpec
from openapi_server.models.service_update_status import ServiceUpdateStatus
from openapi_server import util

from openapi_server.models.object_version import ObjectVersion  # noqa: E501
from openapi_server.models.service_endpoint import ServiceEndpoint  # noqa: E501
from openapi_server.models.service_spec import ServiceSpec  # noqa: E501
from openapi_server.models.service_update_status import ServiceUpdateStatus  # noqa: E501

class Service(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_at=None, endpoint=None, id=None, spec=None, update_status=None, updated_at=None, version=None):  # noqa: E501
        """Service - a model defined in OpenAPI

        :param created_at: The created_at of this Service.  # noqa: E501
        :type created_at: str
        :param endpoint: The endpoint of this Service.  # noqa: E501
        :type endpoint: ServiceEndpoint
        :param id: The id of this Service.  # noqa: E501
        :type id: str
        :param spec: The spec of this Service.  # noqa: E501
        :type spec: ServiceSpec
        :param update_status: The update_status of this Service.  # noqa: E501
        :type update_status: ServiceUpdateStatus
        :param updated_at: The updated_at of this Service.  # noqa: E501
        :type updated_at: str
        :param version: The version of this Service.  # noqa: E501
        :type version: ObjectVersion
        """
        self.openapi_types = {
            'created_at': str,
            'endpoint': ServiceEndpoint,
            'id': str,
            'spec': ServiceSpec,
            'update_status': ServiceUpdateStatus,
            'updated_at': str,
            'version': ObjectVersion
        }

        self.attribute_map = {
            'created_at': 'CreatedAt',
            'endpoint': 'Endpoint',
            'id': 'ID',
            'spec': 'Spec',
            'update_status': 'UpdateStatus',
            'updated_at': 'UpdatedAt',
            'version': 'Version'
        }

        self._created_at = created_at
        self._endpoint = endpoint
        self._id = id
        self._spec = spec
        self._update_status = update_status
        self._updated_at = updated_at
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'Service':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Service of this Service.  # noqa: E501
        :rtype: Service
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this Service.


        :return: The created_at of this Service.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this Service.


        :param created_at: The created_at of this Service.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def endpoint(self) -> ServiceEndpoint:
        """Gets the endpoint of this Service.


        :return: The endpoint of this Service.
        :rtype: ServiceEndpoint
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint: ServiceEndpoint):
        """Sets the endpoint of this Service.


        :param endpoint: The endpoint of this Service.
        :type endpoint: ServiceEndpoint
        """

        self._endpoint = endpoint

    @property
    def id(self) -> str:
        """Gets the id of this Service.


        :return: The id of this Service.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Service.


        :param id: The id of this Service.
        :type id: str
        """

        self._id = id

    @property
    def spec(self) -> ServiceSpec:
        """Gets the spec of this Service.


        :return: The spec of this Service.
        :rtype: ServiceSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec: ServiceSpec):
        """Sets the spec of this Service.


        :param spec: The spec of this Service.
        :type spec: ServiceSpec
        """

        self._spec = spec

    @property
    def update_status(self) -> ServiceUpdateStatus:
        """Gets the update_status of this Service.


        :return: The update_status of this Service.
        :rtype: ServiceUpdateStatus
        """
        return self._update_status

    @update_status.setter
    def update_status(self, update_status: ServiceUpdateStatus):
        """Sets the update_status of this Service.


        :param update_status: The update_status of this Service.
        :type update_status: ServiceUpdateStatus
        """

        self._update_status = update_status

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this Service.


        :return: The updated_at of this Service.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this Service.


        :param updated_at: The updated_at of this Service.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def version(self) -> ObjectVersion:
        """Gets the version of this Service.


        :return: The version of this Service.
        :rtype: ObjectVersion
        """
        return self._version

    @version.setter
    def version(self, version: ObjectVersion):
        """Sets the version of this Service.


        :param version: The version of this Service.
        :type version: ObjectVersion
        """

        self._version = version
