from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegisteredWebhook(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_webhook_id=None, errors=None):  # noqa: E501
        """RegisteredWebhook - a model defined in OpenAPI

        :param created_webhook_id: The created_webhook_id of this RegisteredWebhook.  # noqa: E501
        :type created_webhook_id: int
        :param errors: The errors of this RegisteredWebhook.  # noqa: E501
        :type errors: List[str]
        """
        self.openapi_types = {
            'created_webhook_id': int,
            'errors': List[str]
        }

        self.attribute_map = {
            'created_webhook_id': 'createdWebhookId',
            'errors': 'errors'
        }

        self._created_webhook_id = created_webhook_id
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'RegisteredWebhook':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisteredWebhook of this RegisteredWebhook.  # noqa: E501
        :rtype: RegisteredWebhook
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_webhook_id(self) -> int:
        """Gets the created_webhook_id of this RegisteredWebhook.

        The ID of the webhook. Returned if the webhook is created.  # noqa: E501

        :return: The created_webhook_id of this RegisteredWebhook.
        :rtype: int
        """
        return self._created_webhook_id

    @created_webhook_id.setter
    def created_webhook_id(self, created_webhook_id: int):
        """Sets the created_webhook_id of this RegisteredWebhook.

        The ID of the webhook. Returned if the webhook is created.  # noqa: E501

        :param created_webhook_id: The created_webhook_id of this RegisteredWebhook.
        :type created_webhook_id: int
        """

        self._created_webhook_id = created_webhook_id

    @property
    def errors(self) -> List[str]:
        """Gets the errors of this RegisteredWebhook.

        Error messages specifying why the webhook creation failed.  # noqa: E501

        :return: The errors of this RegisteredWebhook.
        :rtype: List[str]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[str]):
        """Sets the errors of this RegisteredWebhook.

        Error messages specifying why the webhook creation failed.  # noqa: E501

        :param errors: The errors of this RegisteredWebhook.
        :type errors: List[str]
        """

        self._errors = errors
