from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.user_details import UserDetails
from openapi_server import util

from openapi_server.models.user_details import UserDetails  # noqa: E501

class Watchers(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, is_watching=None, _self=None, watch_count=None, watchers=None):  # noqa: E501
        """Watchers - a model defined in OpenAPI

        :param is_watching: The is_watching of this Watchers.  # noqa: E501
        :type is_watching: bool
        :param _self: The _self of this Watchers.  # noqa: E501
        :type _self: str
        :param watch_count: The watch_count of this Watchers.  # noqa: E501
        :type watch_count: int
        :param watchers: The watchers of this Watchers.  # noqa: E501
        :type watchers: List[UserDetails]
        """
        self.openapi_types = {
            'is_watching': bool,
            '_self': str,
            'watch_count': int,
            'watchers': List[UserDetails]
        }

        self.attribute_map = {
            'is_watching': 'isWatching',
            '_self': 'self',
            'watch_count': 'watchCount',
            'watchers': 'watchers'
        }

        self._is_watching = is_watching
        self.__self = _self
        self._watch_count = watch_count
        self._watchers = watchers

    @classmethod
    def from_dict(cls, dikt) -> 'Watchers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Watchers of this Watchers.  # noqa: E501
        :rtype: Watchers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_watching(self) -> bool:
        """Gets the is_watching of this Watchers.

        Whether the calling user is watching this issue.  # noqa: E501

        :return: The is_watching of this Watchers.
        :rtype: bool
        """
        return self._is_watching

    @is_watching.setter
    def is_watching(self, is_watching: bool):
        """Sets the is_watching of this Watchers.

        Whether the calling user is watching this issue.  # noqa: E501

        :param is_watching: The is_watching of this Watchers.
        :type is_watching: bool
        """

        self._is_watching = is_watching

    @property
    def _self(self) -> str:
        """Gets the _self of this Watchers.

        The URL of these issue watcher details.  # noqa: E501

        :return: The _self of this Watchers.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the _self of this Watchers.

        The URL of these issue watcher details.  # noqa: E501

        :param _self: The _self of this Watchers.
        :type _self: str
        """

        self.__self = _self

    @property
    def watch_count(self) -> int:
        """Gets the watch_count of this Watchers.

        The number of users watching this issue.  # noqa: E501

        :return: The watch_count of this Watchers.
        :rtype: int
        """
        return self._watch_count

    @watch_count.setter
    def watch_count(self, watch_count: int):
        """Sets the watch_count of this Watchers.

        The number of users watching this issue.  # noqa: E501

        :param watch_count: The watch_count of this Watchers.
        :type watch_count: int
        """

        self._watch_count = watch_count

    @property
    def watchers(self) -> List[UserDetails]:
        """Gets the watchers of this Watchers.

        Details of the users watching this issue.  # noqa: E501

        :return: The watchers of this Watchers.
        :rtype: List[UserDetails]
        """
        return self._watchers

    @watchers.setter
    def watchers(self, watchers: List[UserDetails]):
        """Sets the watchers of this Watchers.

        Details of the users watching this issue.  # noqa: E501

        :param watchers: The watchers of this Watchers.
        :type watchers: List[UserDetails]
        """

        self._watchers = watchers
