/*
 * Intel Product Catalogue Service
 *
 * This is the documentation for PIM Micro services. In order to use this tool you need to have Basic Auth credentials and a client id. If you dont have one, please make sure to request one by sending an email to the PIM MS team: [pim.360.team@intel.com](mailto:pim.360.team@intel.com?subject=PIMServices)
 *
 * API version: 0.1.0
 * Contact: pim.360.team@intel.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ProductListingLevelInfo struct {

	PageNo string `json:"page_no"`

	PerPage int32 `json:"per_page"`

	// Multiple objects with product data.
	Result []ProductListingLevelInfoResultInner `json:"result"`

	Status string `json:"status"`

	TotalCount int32 `json:"total_count"`
}

// AssertProductListingLevelInfoRequired checks if the required fields are not zero-ed
func AssertProductListingLevelInfoRequired(obj ProductListingLevelInfo) error {
	elements := map[string]interface{}{
		"page_no": obj.PageNo,
		"per_page": obj.PerPage,
		"result": obj.Result,
		"status": obj.Status,
		"total_count": obj.TotalCount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Result {
		if err := AssertProductListingLevelInfoResultInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertProductListingLevelInfoConstraints checks if the values respects the defined constraints
func AssertProductListingLevelInfoConstraints(obj ProductListingLevelInfo) error {
	return nil
}
