/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AppUpdateRequestDataRelationships : IEquatable<AppUpdateRequestDataRelationships>
    {
        /// <summary>
        /// Gets or Sets AvailableTerritories
        /// </summary>
        [DataMember(Name="availableTerritories", EmitDefaultValue=false)]
        public AppUpdateRequestDataRelationshipsAvailableTerritories AvailableTerritories { get; set; }

        /// <summary>
        /// Gets or Sets Prices
        /// </summary>
        [DataMember(Name="prices", EmitDefaultValue=false)]
        public AppUpdateRequestDataRelationshipsPrices Prices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AppUpdateRequestDataRelationships {\n");
            sb.Append("  AvailableTerritories: ").Append(AvailableTerritories).Append("\n");
            sb.Append("  Prices: ").Append(Prices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AppUpdateRequestDataRelationships)obj);
        }

        /// <summary>
        /// Returns true if AppUpdateRequestDataRelationships instances are equal
        /// </summary>
        /// <param name="other">Instance of AppUpdateRequestDataRelationships to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AppUpdateRequestDataRelationships other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AvailableTerritories == other.AvailableTerritories ||
                    AvailableTerritories != null &&
                    AvailableTerritories.Equals(other.AvailableTerritories)
                ) && 
                (
                    Prices == other.Prices ||
                    Prices != null &&
                    Prices.Equals(other.Prices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AvailableTerritories != null)
                    hashCode = hashCode * 59 + AvailableTerritories.GetHashCode();
                    if (Prices != null)
                    hashCode = hashCode * 59 + Prices.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AppUpdateRequestDataRelationships left, AppUpdateRequestDataRelationships right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AppUpdateRequestDataRelationships left, AppUpdateRequestDataRelationships right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
