/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<Platform>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum Platform
        {
            
            /// <summary>
            /// Enum IOSEnum for IOS
            /// </summary>
            [EnumMember(Value = "IOS")]
            IOSEnum = 1,
            
            /// <summary>
            /// Enum MACOSEnum for MAC_OS
            /// </summary>
            [EnumMember(Value = "MAC_OS")]
            MACOSEnum = 2,
            
            /// <summary>
            /// Enum TVOSEnum for TV_OS
            /// </summary>
            [EnumMember(Value = "TV_OS")]
            TVOSEnum = 3
        }
}
