/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type LiveStreamResponse struct {

	MediaSource MediaSourceInfo `json:"MediaSource,omitempty"`
}

// AssertLiveStreamResponseRequired checks if the required fields are not zero-ed
func AssertLiveStreamResponseRequired(obj LiveStreamResponse) error {
	if err := AssertMediaSourceInfoRequired(obj.MediaSource); err != nil {
		return err
	}
	return nil
}

// AssertLiveStreamResponseConstraints checks if the values respects the defined constraints
func AssertLiveStreamResponseConstraints(obj LiveStreamResponse) error {
	return nil
}
