/*
 * Radio & Music Services
 *
 * We encapsulate Radio & Music business logic for iPlayer Radio and BBC Music products on all platforms. We add value by reliably providing the right blend of metadata needed by clients.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type NetworkSummary struct {

	Active bool `json:"active"`

	Group string `json:"group"`

	Id string `json:"id"`

	Key string `json:"key"`

	Titles NetworkTitles `json:"titles"`

	Type string `json:"type"`
}

// AssertNetworkSummaryRequired checks if the required fields are not zero-ed
func AssertNetworkSummaryRequired(obj NetworkSummary) error {
	elements := map[string]interface{}{
		"active": obj.Active,
		"group": obj.Group,
		"id": obj.Id,
		"key": obj.Key,
		"titles": obj.Titles,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkTitlesRequired(obj.Titles); err != nil {
		return err
	}
	return nil
}

// AssertNetworkSummaryConstraints checks if the values respects the defined constraints
func AssertNetworkSummaryConstraints(obj NetworkSummary) error {
	return nil
}
